import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import '../viewmodels/auth_provider.dart' as custom_auth;
import '../services/pengaduan_service.dart';
import '../services/notification_service.dart';
import '../model/pengaduan_model.dart';
import '../style/colors.dart';
import '../style/text_style.dart';
import '../widget/bottom_navbar.dart';



class PengaduanPage extends StatefulWidget {
  final String kategori;

  const PengaduanPage({
    super.key,
    required this.kategori,
  });

  @override
  State<PengaduanPage> createState() => _PengaduanPageState();
}

class _PengaduanPageState extends State<PengaduanPage> {
  late TextEditingController _judulController;
  late TextEditingController _deskripsiController;

  @override
  void initState() {
    super.initState();
    _judulController = TextEditingController();
    _deskripsiController = TextEditingController();
  }

  @override
  void dispose() {
    _judulController.dispose();
    _deskripsiController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Form Pengaduan',
          style: AppTextStyles.headline1,
        ),
        backgroundColor: AppColors.primary,
        centerTitle: true,
      ),
      bottomNavigationBar: const CustomBottomNavBar(currentIndex: 0),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Kategori: ${widget.kategori}',
              style: AppTextStyles.bodyText.copyWith(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            Text(
              'Judul Pengaduan',
              style: AppTextStyles.bodyText.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            TextField(
              controller: _judulController,
              decoration: InputDecoration(
                hintText: 'Masukkan judul pengaduan',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
            const SizedBox(height: 16),
            Text(
              'Deskripsi Pengaduan',
              style: AppTextStyles.bodyText.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            TextField(
              controller: _deskripsiController,
              decoration: InputDecoration(
                hintText: 'Jelaskan detail pengaduan anda',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
              maxLines: 5,
            ),
            const SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: () async {
                  if (_judulController.text.isEmpty || _deskripsiController.text.isEmpty) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('Mohon isi judul dan deskripsi pengaduan.'),
                        backgroundColor: Colors.red,
                      ),
                    );
                    return;
                  }

                  // Show loading dialog
                  showDialog(
                    context: context,
                    barrierDismissible: false,
                    builder: (context) => const Center(child: CircularProgressIndicator()),
                  );
                  
                  try {
                    final authProvider = context.read<custom_auth.AuthProvider>();
                    final userId = authProvider.currentUserData?.uid ?? FirebaseAuth.instance.currentUser?.uid;
                    final nik = authProvider.currentUserData?.nik;

                    if (userId == null) {
                      Navigator.pop(context); // close loading
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text('Anda harus login untuk membuat pengaduan')),
                      );
                      return;
                    }

                    final newPengaduan = PengaduanModel(
                      id: '', // Will be generated by Firestore
                      judul: _judulController.text,
                      keluhan: _deskripsiController.text,
                      status: 'Sedang Diproses',
                      userId: userId,
                      nik: nik ?? '',
                      createdAt: DateTime.now(),
                    );

                    await PengaduanService().submitPengaduan(newPengaduan);

                    // Buat Notifikasi
                    await NotificationService().sendNotification(
                      userId: userId,
                      title: 'Pengaduan Terkirim',
                      body: 'Pengaduan "${_judulController.text}" berhasil dikirim dan sedang diproses.',
                    );

                    // Close loading dialog
                    if (context.mounted) Navigator.pop(context);

                    // Show success dialog
                    if (context.mounted) {
                      showDialog(
                        context: context,
                        barrierDismissible: false,
                        builder: (context) => AlertDialog(
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                      title: const Icon(Icons.check_circle, color: AppColors.primary, size: 64),
                      content: const Text(
                        'Pengaduan Berhasil Dikirim',
                        textAlign: TextAlign.center,
                        style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                      ),
                      actions: [
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton(
                            onPressed: () {
                              // Navigate back to Dashboard (pop twice)
                              Navigator.of(context).popUntil((route) => route.isFirst);
                            },
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primary,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Text('Kembali ke Beranda', style: TextStyle(color: Colors.white)),
                          ),
                        ),
                      ],
                    ),
                  );
                }
              } catch (e) {
                if (context.mounted) {
                  Navigator.pop(context); // close loading dialog
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Gagal mengirim pengaduan: $e')),
                  );
                }
              }
            },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  padding: const EdgeInsets.symmetric(vertical: 16), // Made it slightly taller for better UX
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: const Text(
                  'Kirim Pengaduan',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}